name: integrated_home
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  firebase_database: ^11.3.4
  firebase_app_check: ^0.3.2+5
  provider: ^6.1.1
  flutter_local_notifications: ^17.0.0

  image: ^4.0.17
  synchronized: ^3.0.0
  logging: ^1.2.0
  path_provider: ^2.1.0
  ffi: ^2.1.0
  onnxruntime: ^1.4.1
  flutter_vlc_player: ^7.2.0
  google_mlkit_face_detection: ^0.13.0
  google_mlkit_commons: ^0.11.0
  collection: ^1.18.0
  cloud_functions: 5.5.0
  intl: ^0.18.1
  uuid: ^3.0.7
  flutter_image_compress: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
