// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAikvD2huFKUqJc-w31nSqLS-haLz0eokE',
    appId: '1:763164912972:web:0ccaff7468c17006ef73e9',
    messagingSenderId: '763164912972',
    projectId: 'integrated-home-b9159',
    authDomain: 'integrated-home-b9159.firebaseapp.com',
    storageBucket: 'integrated-home-b9159.firebasestorage.app',
    measurementId: 'G-YWW15P9YJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZp44n49WBwyiOIZ8ukpHO60m-NJb7ZI4',
    appId: '1:763164912972:android:6a41e2c318681b78ef73e9',
    messagingSenderId: '763164912972',
    projectId: 'integrated-home-b9159',
    storageBucket: 'integrated-home-b9159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rugGEGXLFjuEc5VsptMEalke_gTqLCc',
    appId: '1:763164912972:ios:f7a2df5ecf8c1637ef73e9',
    messagingSenderId: '763164912972',
    projectId: 'integrated-home-b9159',
    storageBucket: 'integrated-home-b9159.firebasestorage.app',
    iosBundleId: 'com.example.integratedHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5rugGEGXLFjuEc5VsptMEalke_gTqLCc',
    appId: '1:763164912972:ios:f7a2df5ecf8c1637ef73e9',
    messagingSenderId: '763164912972',
    projectId: 'integrated-home-b9159',
    storageBucket: 'integrated-home-b9159.firebasestorage.app',
    iosBundleId: 'com.example.integratedHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAikvD2huFKUqJc-w31nSqLS-haLz0eokE',
    appId: '1:763164912972:web:e2cc0152ea8ec7e5ef73e9',
    messagingSenderId: '763164912972',
    projectId: 'integrated-home-b9159',
    authDomain: 'integrated-home-b9159.firebaseapp.com',
    storageBucket: 'integrated-home-b9159.firebasestorage.app',
    measurementId: 'G-DS6Y1TGQ6S',
  );
}
